name: Publish Presentations to Pages

on:
  push:
    branches: ["main","800-file-gorilla"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

    # Publish reveal-md presentations
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Build Static Presentations
        shell: pwsh
        run: 'Get-ChildItem ./slides -directory | foreach { Write-Host "Publishing $_" && npm run publish $_.Name }'

    # Push to GH pages
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './publish'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
